# Site settings
author: Kinnari
title: My blog
header-img: img/home-bg.png
email: kinnari1022@yahoo.com
copyright_name: Kinnari
description: > # this means to ignore newlines until "baseurl:"
  My Journey Through Coding School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Kiki1022

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
